version: "2"
services:
  web:
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: